---
type: opt # single|window, maybe add opt
key: unarm #added to the csv names
evaluation: evaluation_user_based #evaluation|evaluation_last|evaluation_multiple|evaluation_user_based|evaluation_user_based_multiple
data:
  name: xing #added in the end of the csv names
  folder: data/xing/xing2016/prepared/
  prefix: interactions
  type: hdf #hdf (if there is no type, the default is csv)

results:
  folder: results/opt/xing/unarm_reminder/

metrics:
- class: accuracy_multiple.Precision
  length: [5,10,15,20]
- class: accuracy_multiple.Recall
  length: [5,10,15,20]
- class: accuracy_multiple.MAP
  length: [5,10,15,20]
- class: accuracy.HitRate
  length: [5,10,15,20]
- class: accuracy.MRR
  length: [5,10,15,20]

optimize:
  class: accuracy.MRR
  length: [20]
  iterations: 100 #optional

algorithms:
- class: narm.unarm.UNARM
  params: { epochs: 20, reminders: True, remind_strategy: 'recency' }
  params_opt:
    factors: [50, 100]
    lr: [{from: 0.01, to: 0.001, in: 10, type: float32},{from: 0.0001, to: 0.001, in: 10, type: float32}]
    extend_session_length: {from: 1, to: 25, in: 25, type: int32}
    remind_mode: ['top', 'end']
    remind_sessions_num: {from: 1, to: 10, in: 10, type: int32}
    reminders_num: {from: 1, to: 5, in: 5, type: int32}
  key: unarm