---
type: opt # single|window, maybe add opt
key: csrm #added to the csv names
evaluation: evaluation #evaluation|evaluation_last|evaluation_multiple
data:
  name: 8tracks-window #added in the end of the csv names
  folder: data/8tracks/single/
  prefix: playlists-8tracks 
  opts: {sessions_test: 5000}

results:
  folder: results/opt/8tracks_window/

metrics:
- class: accuracy.HitRate
  length: [5,10,15,20]
- class: accuracy.MRR
  length: [5,10,15,20]
- class: coverage.Coverage
  length: [20]
- class: popularity.Popularity
  length: [20]
- class: time_memory_usage.Time_usage_training
- class: time_memory_usage.Time_usage_testing
#- class: time_memory_usage.Memory_usage


optimize:
  class: accuracy.MRR
  length: [20]
  iterations: 50 #optional

algorithms:
- class: CSRM.csrm.CSRM
  params: { hidden_units: 100, epoch: 10 }#, batch_size: 256 }
  params_opt:
    lr: [{from: 0.001, to: 0.0001, in: 10, type: float32},{from: 0.0001, to: 0.00001, in: 10, type: float32}]
    memory_size: [128,256,512]
  key: csrm

