---
type: opt # single|window, maybe add opt
key: csrm #added to the csv names
evaluation: evaluation #evaluation|evaluation_last|evaluation_multiple
data:
  name: nowplaying #added in the end of the csv names
  folder: data/nowplaying/single/
  prefix: nowplaying
  opts: {sessions_test: 5000}

results:
  folder: results/csrm/opt/nowplaying/

metrics:
- class: accuracy.HitRate
  length: [3,5,10,15,20]
- class: accuracy.MRR
  length: [3,5,10,15,20]
- class: coverage.Coverage
  length: [20]
- class: popularity.Popularity
  length: [20]
- class: time_memory_usage.Time_usage_training
- class: time_memory_usage.Time_usage_testing
#- class: time_memory_usage.Memory_usage

optimize:
  class: accuracy.MRR
  length: [20]
  iterations: 100 #optional

algorithms:
- class: CSRM.csrm.CSRM
  params: { hidden_units: 100, epoch: 10}
  params_opt:
    lr: [{from: 0.001, to: 0.0001, in: 10, type: float32},{from: 0.0001, to: 0.00001, in: 10, type: float32}]
    memory_size: [128,256,512]
  key: csrm

