---
type: opt # single|window, maybe add opt
key: ugru4rec_reminders #added to the csv names
evaluation: evaluation_user_based #evaluation|evaluation_last|evaluation_multiple|evaluation_user_based|evaluation_user_based_multiple
data:
  name: xing #added in the end of the csv names
  folder: data/xing/xing2016/prepared/
  prefix: interactions
  type: hdf #hdf (if there is no type, the default is csv)

results:
  folder: results/opt/xing/ugru4rec_reminders/

metrics:
- class: accuracy_multiple.Precision
  length: [5,10,15,20]
- class: accuracy_multiple.Recall
  length: [5,10,15,20]
- class: accuracy_multiple.MAP
  length: [5,10,15,20]
- class: accuracy.HitRate
  length: [5,10,15,20]
- class: accuracy.MRR
  length: [5,10,15,20]


optimize:
  class: accuracy.MRR
  length: [20]
  iterations: 100 #optional

algorithms:
- class: gru4rec.ugru4rec.UGRU4Rec
  params: {reminders: True, remind_strategy: 'recency'}
  params_opt:
    loss: ['bpr-max', 'top1-max']
    final_act: ['elu-0.5','linear']
    dropout_p_hidden: {from: 0.0, to: 0.9, in: 10, type: float}
    momentum: {from: 0.0, to: 0.9, in: 10, type: float32}
    learning_rate: [ {from: 0.1, to: 0.01, in: 10, type: float32}, {from: 0.5, to: 0.1, in: 5, type: float32} ]
    constrained_embedding: [True,False]
    extend_session_length: {from: 1, to: 25, in: 25, type: int32}
    remind_mode: ['top', 'end']
    remind_sessions_num: {from: 1, to: 10, in: 10, type: int32}
    reminders_num: {from: 1, to: 5, in: 5, type: int32}
  key: ugru4rec_reminders
